WND_WIDTH, WND_HEIGHT = 800, 600


BACKGROUND_COLOR = (0,0,0)
GRID_COLOR = (30, 30, 30)
WALL_DEFAULT_COLOR = (255, 255, 255)

MAP_SCALE = 5

SELECTED_WALL_WIDTH = 2
SELECTED_POINT_R_PX = 4
SELECTED_POINT_R_UNITS = SELECTED_POINT_R_PX/MAP_SCALE


GRID_CELL_UNIT_SIZE = 10
GRID_CELL_PX_SIZE =  GRID_CELL_UNIT_SIZE * MAP_SCALE
GRID_DOT_RADIUS_PX = 2

CURSOR_RADIUS_PX = 3
CURSOR_RADIUS_UNITS = CURSOR_RADIUS_PX / MAP_SCALE
