WND_WIDTH, WND_HEIGHT = 800, 600


BACKGROUND_COLOR = (0,0,0)
GRID_COLOR = (30,30,30)


MAP_SCALE = 5

GRID_CELL_UNIT_SIZE = 10
GRID_CELL_PX_SIZE =  GRID_CELL_UNIT_SIZE * MAP_SCALE
GRID_DOT_RADIUS_PX = 2

CURSOR_RADIUS_PX = 3
CURSOR_RADIUS_UNITS = CURSOR_RADIUS_PX / MAP_SCALE
